name: remiderapp
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 
  intl: 
  sqflite: 
  auto_size_text: 
  path: 
  flutter_local_notifications: 
  timezone: 
  animated_text_kit: 
  animated_widgets: 

dev_dependencies:
  flutter_test:
    sdk: flutter
 
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/images/
  
  fonts:
    - family: Popins
      fonts:
        - asset: assets/fonts/popins_regular.ttf
        - asset: assets/fonts/popins_light.ttf
          weight: 300
        - asset: assets/fonts/popins_bold.ttf
          weight: 700
        - asset: assets/fonts/popins_semibold.ttf
          weight: 600
        - asset: assets/fonts/popins_medium.ttf
          weight: 500

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  #
  
  
